#xiang.fei@Multimedia, 2015/10/16, Add for nxp
include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-$(CONFIG_MTK_SOUND) += AudDrv_NXP.o

obj-$(CONFIG_ARCH_MT6595) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
